version: '3.8'

services:
  node:
    user: $UID:$GID
    image: node:14-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - $PORT:8080
    environment:
      - PORT=$PORT
    command: [ "npm", "run", "start" ]
